"""empty message

Revision ID: 758f3b378409
Revises: 7c0f00fb286a
Create Date: 2020-12-15 18:51:47.247888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758f3b378409'
down_revision = '7c0f00fb286a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique genre", ['genre_type'])

    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique model", ['model_type'])

    with op.batch_alter_table('platform', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique platform", ['platform_name'])

    with op.batch_alter_table('developer', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique developer", ['name'])

    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique publisher", ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publisher', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('platform', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('developer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
