"""empty message

Revision ID: 7c0f00fb286a
Revises: 68a2befcc78d
Create Date: 2020-12-15 18:10:53.441934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0f00fb286a'
down_revision = '68a2befcc78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer',
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('developer_id')
    )
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('genre_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_table('model',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('platform',
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('platform_id')
    )
    op.create_table('publisher',
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('publisher_id')
    )
    op.create_table('game',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('developer', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['developer'], ['developer.developer_id'], ),
    sa.ForeignKeyConstraint(['publisher'], ['publisher.publisher_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('game_genre',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], )
    )
    op.create_table('game_model',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.model_id'], )
    )
    op.create_table('game_platform',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.platform_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_platform')
    op.drop_table('game_model')
    op.drop_table('game_genre')
    op.drop_table('game')
    op.drop_table('publisher')
    op.drop_table('platform')
    op.drop_table('model')
    op.drop_table('genre')
    op.drop_table('developer')
    # ### end Alembic commands ###
