"""empty message

Revision ID: e10b82078cfb
Revises: 
Create Date: 2020-12-23 23:30:22.554829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10b82078cfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer',
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('developer_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('game',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('genre_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('genre_id'),
    sa.UniqueConstraint('genre_type')
    )
    op.create_table('model',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('model_type')
    )
    op.create_table('platform',
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('platform_id'),
    sa.UniqueConstraint('platform_name')
    )
    op.create_table('publisher',
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('publisher_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=35), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('game_developer',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developer.developer_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], )
    )
    op.create_table('game_genre',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], )
    )
    op.create_table('game_model',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.model_id'], )
    )
    op.create_table('game_platform',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.platform_id'], )
    )
    op.create_table('game_publisher',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.publisher_id'], )
    )
    op.create_table('user_game',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_game')
    op.drop_table('game_publisher')
    op.drop_table('game_platform')
    op.drop_table('game_model')
    op.drop_table('game_genre')
    op.drop_table('game_developer')
    op.drop_table('user')
    op.drop_table('publisher')
    op.drop_table('platform')
    op.drop_table('model')
    op.drop_table('genre')
    op.drop_table('game')
    op.drop_table('developer')
    # ### end Alembic commands ###
